grpc:
  server:
    port: 9090
spring:
  application:
    name: test-microservicetes
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    web-application-type: NONE
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8004/realms/test-realm
      client:
        provider:
          service-client:
            issuer-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}
        registration:
          service-client:
            client-name: service-client
            client-id: service-client
            client-secret: service-client-secret
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            scope:
              - openid