# This workflow will build a package using npm and then publish it to npmjs packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release - Publish NPM Package to npmjs Repository
on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - id: Checkout
      name: Checkout
      uses: actions/checkout@v4
          
    - id: Setup_Node_20
      name: Set up Node 20
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: web/angular/
        node-version: 20
        cache: 'npm'
        registry-url: ${{vars.NPM_REPOSITORY_URL}}

    - id: Cache_NPM_Packages
      name: Cache NPM Packages
      uses: actions/cache@v4
      with:        
        path: '~/.npm'
        key: ${{ runner.os }}-${{ matrix.node-version }}-9.8.0-npmcache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - id: Install_Angular_cli
      name: Install Angular cli
      working-directory: web/angular/
      run: npm install -g @angular/cli@latest

    - id: Publish_to_Repository
      name: Publish to Repository
      env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REPOSITORY_TOKEN}}
      working-directory: web/angular/
      run: ./ng-publish.sh
